In [1]:
class xyz:
    def __init__(self,a,b,c):
        self.a=a
        self.b=b 
        self.c=c 
    def test(self):
        p;rint("this is muy first test motion of xyz class")
    
    def test1(self):
        print("this is a test1 math of xyz class")
        
    def test2(self):
        print("this is my test2 math of xyz class")

In [2]:
p=xyz(1,2,3)

In [4]:
p.test1()

this is a test1 math of xyz class


In [9]:
class xyz1(xyz):
    pass

In [10]:
q=xyz1()

TypeError: __init__() missing 3 required positional arguments: 'a', 'b', and 'c'

In [11]:
q=xyz1(3,4,5)

In [12]:
q.test1()

this is a test1 math of xyz class


In [13]:
class xyz1(xyz):
    def test(self):
        print("this is a test meth avilable in xyz1 ")
        

In [14]:
g =xyz1(4,5,6)

In [15]:
g.test()

this is a test meth avilable in xyz1 


In [6]:
class xyz:
    def __init__(self,a,b,c):
        self.a=a 
        self.b=b 
        self.c=c 
        
        
    def test(self):
        print("this is a meth of xyz class")
        
class xyz1:
    
    def __init__(self,p,q,v):
        self.p=p 
        self.q=q 
        self.v=v
        
    def test1(self):
        print("this is a meth form class xyz1")
        
class child(xyz1,xyz):
    def __init__(self,*args,**kwargs):
        xyz.__init__(self,*args)
        xyz1.__init__(self,**kwargs)
        

In [8]:
n=child(4,5,6,p=3,q=4,v=5)

In [9]:
n.p

3

In [10]:
n.q

4

In [11]:
n.v

5

In [19]:
class xyz:
    def __init__(self,a,b,c):
        self.a=a 
        self.b=b 
        self.c=c 
        
        
    def test(self):
        print("this is a meth of xyz class")
        
class xyz1(xyz):
    
    def test1(self):
        print("this is  a meth form class xyz1")
        
class xyz2(xyz1):
    def test2(self):
        print("this is a meth form class 2")
        
class xyz3(xyz2):
    def test3(self):
        print("this is my meth form class xyz3")
        

In [20]:
v=xyz2(5,6,7)

In [22]:
m=xyz3(4,5,6)

In [ ]:
q1- create a file class for reading data forom respective file with a method name read and write.
q2- try to inherit read and write method form parent class to child class to operform read and write operation

In [24]:
class readFile:
    def __init__(self,fileObj, lines):
        self.file = fileObj
        self.lines = lines
    def readFile(self):
        file2=open(self.file,'r')
        line=file2.readline()
        while(line!=""):
            print(line)
            line=file2.readline()

    def writeFile(self):
        content_write = open(self.file,'w')
        content_write.writelines(lines)
        content_write.close()
        
class readFile1(readFile):
    def readFile1(self):
        print("inheritance of readFile class")

file1 = r'test1.txt'
lines = 'Inserted Lines .......'

read_write = readFile1(file1,lines)
read_write.writeFile()
read_write.readFile()

        

Inserted Lines .......


In [1]:
class test :
    def __init__(self,a,b,c):
        self.a=a
        self.b=b 
        self.c= c 
        
class test1(test):
    pass
u=test(4,5,6)

In [2]:
v=test1(3,4,5)

In [32]:
class test :
    def __init__(self):
        self.__a=4
        
class test1(test):
    def __init__(self):
        self.__a=7
u=test()

In [33]:
u.a

AttributeError: 'test' object has no attribute 'a'

In [34]:
v=test1()

In [35]:
v.a

AttributeError: 'test1' object has no attribute 'a'

In [42]:
class test:
    def __init__(self,a,b,c):
        self._a=a 
        self.__b=b 
        self.c=c 
    
class test1(test):
    pass
v = test(4,5,6)

In [43]:
v._a

4

In [57]:
u._test__b

4

In [56]:
v._test__b

5

In [45]:
v.c

6

In [50]:
u=test1(3,4,7)

In [51]:
u.c

7

In [52]:
u._a

3

In [54]:
u._test1__b

AttributeError: 'test1' object has no attribute '_test1__b'

In [58]:
class bonousclaculator:
    def __init__(self, empid , emprating) :
        self.empid = empid
        self.emprating = emprating
        self._empmail = "fdsfsfssf@gmail.com"
        self.__bonusforratingA = "70%"
        self.__bonusforraringB = "60%"
        self.__bonusforratinC = "40%"
    
    def bonuscalculator(self) :
        if self.emprating == "A":
            bonus = self.__bonusforratingA
            return bonus
        elif self.emprating == "B" :
            bonus = self.__bonusforraringB
            return bonus
        else :
            bonus = self.__bonusforratinC
            return bonus

In [59]:
emp1 = bonousclaculator(101 , "A")
emp2 = bonousclaculator(102 , "B")
emp3 = bonousclaculator(103, "C")

In [60]:
emp1.bonuscalculator()

'70%'

In [61]:
emp2.bonuscalculator()

'60%'

In [62]:
emp3.bonuscalculator()

'40%'

In [63]:
emp1.empid = 104

In [70]:
emp1.empid

104

In [65]:
emp1.emprating= "B"

In [66]:
emp1.bonuscalculator()

'60%'

In [67]:
emp1.__bonusforraringB = "90%"

In [69]:
emp1.bonuscalculator()

'60%'

In [71]:
emp2.emprating

'B'

In [72]:
emp2.bonuscalculator()

'60%'

In [73]:
emp2= "100%"

In [74]:
emp2.bonuscalculator()

AttributeError: 'str' object has no attribute 'bonuscalculator'

In [75]:
emp2.empid = 34543543

AttributeError: 'str' object has no attribute 'empid'

In [76]:
emp2.empid

AttributeError: 'str' object has no attribute 'empid'

In [77]:
emp2.__bonusforraringB = "fsadfsafs"

AttributeError: 'str' object has no attribute '__bonusforraringB'

In [79]:
emp2._bonousclaculator__bonusforraringB

AttributeError: 'str' object has no attribute '_bonousclaculator__bonusforraringB'

In [80]:
emp2._bonousclaculator__bonusforraringB  = "435456"

AttributeError: 'str' object has no attribute '_bonousclaculator__bonusforraringB'

In [81]:
emp2._bonousclaculator__bonusforraringB 

AttributeError: 'str' object has no attribute '_bonousclaculator__bonusforraringB'

In [82]:
emp1._empmail 

'fdsfsfssf@gmail.com'

In [83]:
emp1._empmail  = "sudhanshu@gmail.com"

In [84]:
emp1._empmail

'sudhanshu@gmail.com'

In [85]:
class xyz():
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
    def test (self):
        print ("machine")

class xyz1(xyz):
    def __init__(self,p,q,r):
        self.p=p
        self.q=q
        self.r=r
    def test1(self):
        print ("learning")
class xyz2(xyz1):
    def test2(self):
        print ("ineuron")


In [86]:
v=xyz2(3,4,5)

In [87]:
v.test()

machine


In [89]:
def checkPrime():
    ''' Checks if a number is Prime. Keeps on asking
        for an input in correct form, >1 & an integer
        '''
    while True:
        try:
            num=int(input('Enter an integer'))
            if num>1:
                for i in range(2, num):
                    
                    if (num % i)==0:
                        pss
                        #print(num, ' is a not prime number')
                        #break
                
                    else:
                        print(num, ' is a prime number')
                        break
                        
                break       
                        
                
            else:
                print('Please enter a number >1')
        except:
            print('Please enter a valid input, an integer')
checkPrime()


Enter an integer4564
Please enter a valid input, an integer
Enter an integer456
Please enter a valid input, an integer
Enter an integer435
435  is a prime number


In [90]:
def largest_arr(*args):
    lagest_list_iter=0
    lagest_list=0
    l=[]
    for i in args:
        if type(i)==list or type(i)==tuple or type(i)==set:
            for j in i:
                l.append(j)
                lagest_list_iter=max(l)
            return lagest_list_iter    
                
        else:
            for i in args:
                l.append(i)
                lagest_list=max(l)
            return lagest_list


In [91]:
a = 50
iter(a)

TypeError: 'int' object is not iterable

In [92]:
b=[4,5,6]

In [93]:
type(iter(b))

list_iterator

In [94]:
if list in [list, tuple,set]:
    print("do something")

do something


In [95]:
import array as arr

In [96]:
a = arr.array('f' , [1,2,3,4])
a

array('f', [1.0, 2.0, 3.0, 4.0])

In [97]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [98]:
np.asanyarray([3,5,67,67])

array([ 3,  5, 67, 67])

In [99]:
np.asanyarray([34,6565,76,7,6])

array([  34, 6565,   76,    7,    6])

In [100]:
for i in a:
    print(i)

1.0
2.0
3.0
4.0


In [101]:
class parent:
    def __init__(self, p, q, r):
        self.p = p
        self._q = q
        self.__r = r
        
class child(parent):
    pass

c1 = child(4,5,6)

# How is  this possible??? 
c1.z = 435
c1.z

435

In [102]:
a=10

In [103]:
c2=child(4,5,6)

In [104]:
c2.z

AttributeError: 'child' object has no attribute 'z'

In [105]:
class bonuscalculator:
    def __init__(self,empid, emprating):
        self.empid = empid
        self.emprating = emprating
        self.__bonusforratingA = "70%"
        self.__bonusforratingB = "60%"
        self.__bonusforratingC = "40%"

    def bonuscalc(self):
        if self.emprating == "A":
            bonus = self.__bonusforratingA
            return bonus
        elif self.emprating == "B":
            bonus = self.__bonusforratingB
            return bonus
        else : 
            bonus = self.__bonusforratingC
            return bonus ,self.empid

emp1 = bonuscalculator(101, "A")
emp2 = bonuscalculator(102, "B")
emp3 = bonuscalculator(103, "C")
emp1.bonuscalc()
emp2.bonuscalc()


'60%'

In [106]:
emp3.bonuscalc()

('40%', 103)

In [107]:
class bonuscalculator:
    def __init__(self,empid,emprating):
        self.empid = empid
        self.emprating = emprating
        self._empmail = "abcd@gmail.com"
        self.__bonusforratingA = "70%"
        self.__bonusforratingB = "60%"
        self.__bonusforratingC = "40%"
        
    def bonuscalculator(self):
        if self.emprating == "A":
            bonus = self.__bonusforratingA
            return bonus ,self.empid
        elif self.emprating == "B":
            bonus = self.__bonusforratingB
            return bonus,self.empid
        else:
            bonus = self.__bonusforratingC
            return bonus,self.empid
emp1 = bonuscalculator(101,"A")
emp2 = bonuscalculator(102,"B")
emp3 = bonuscalculator(103,"C")
emp1.bonuscalculator()
emp2.bonuscalculator()



('60%', 102)

In [108]:
class Xyz:
    objCount = 0
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c
        Xyz.objCount += 1
        
    def test(self):
        print("Inside test method")
        
    def test1(self):
        print("Inside the test1 method")
        
    def test2(self):
        print("Inside the test2 method")

p = Xyz(1,2,3)
p1 = Xyz(2,3,4)
p1.objCount

2

In [109]:
p2 = Xyz(2,3,4)

In [110]:
p1.objCount


3